name: run-cloudflared-sshd
on:
  workflow_dispatch: {}
jobs:
  job-cloudflared-sshd:
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sleep 15
        name: Sleep 15
      - uses: valeriangalliat/action-sshd-cloudflared@master