name: show-installed-stuff
on:
  workflow_dispatch: {}
jobs:
  show-installed-stuff:
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest
    steps:
      - run: compgen -c
      - run: compgen -b
      - run: apropos -s 1 ''
      - run: dpkg -l
      - run: apt list
      - run: snap list
      - run: ex --version
      - run: vim --version
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: nvim -V1 -v
      
